# Generated by Django 5.2.8 on 2025-11-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text="FontAwesome icon class (e.g., 'fas fa-heart')", max_length=50)),
                ('color', models.CharField(default='#3b82f6', help_text='Hex color code for the mood', max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='moods',
            field=models.ManyToManyField(blank=True, related_name='movies', to='core.mood'),
        ),
    ]
