# Generated by Django 5.2.8 on 2025-11-28 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mood_movie_moods'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='movie',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='view_count',
        ),
    ]
