# Generated by Django 5.2.8 on 2025-11-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_movie_options_remove_movie_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
