# Generated by Django 5.2.8 on 2025-11-28 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_movie_trailer_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='video_url',
        ),
    ]
