# Generated by Django 5.2.8 on 2025-11-28 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_movie_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='backdrop_image',
        ),
    ]
