# Generated by Django 5.2.8 on 2025-11-28 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_movie_backdrop_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='backdrop_url',
        ),
    ]
