# Generated by Django 4.2.7 on 2025-11-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_movie_backdrop_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrating',
            options={'ordering': ['-year']},
        ),
        migrations.AddField(
            model_name='userrating',
            name='year',
            field=models.PositiveIntegerField(default=2024),
        ),
    ]
